# Generated by Django 6.0 on 2026-01-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category', 'name']},
        ),
        migrations.RenameField(
            model_name='map',
            old_name='title',
            new_name='map_title',
        ),
        migrations.RemoveField(
            model_name='map',
            name='map_date',
        ),
        migrations.RemoveField(
            model_name='map',
            name='price',
        ),
        migrations.AddField(
            model_name='map',
            name='external_map_id',
            field=models.IntegerField(help_text='ID from Excel source', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='map',
            name='map_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='map_info_memo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='map',
            name='map_maker',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='map_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Listed Price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='map_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='map_year',
            field=models.CharField(blank=True, help_text='year the map depicts', max_length=50),
        ),
        migrations.AddField(
            model_name='map',
            name='planned_use',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('region', 'Region'), ('era', 'Historical Era')], default='region', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'category')},
        ),
    ]
