# Generated by Django 6.0 on 2026-01-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_collection_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='image',
            field=models.ImageField(blank=True, upload_to='maps/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('region', 'Region'), ('state', 'US State'), ('country', 'Country'), ('cont', 'Continent'), ('city', 'City'), ('river', 'River'), ('content', 'Content'), ('era', 'Historical Era'), ('type', 'Print Type'), ('misc', 'Miscellaneous')], default='region', max_length=20),
        ),
    ]
