# Generated by Django 6.0 on 2026-01-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_alter_map_image_alter_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='physical_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
