# Generated by Django 6.0 on 2026-01-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_map_physical_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='map_height',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='map_width',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
